### ISSUE TITLE
Migration to v10. Functional Review status

### ISSUE THREAD

**Issue by AaronHForgeFlow** [ForgeFlow/mailbox_replica#15]
- [x] fetchmail_server_per_user #13 
- [x] smtp_per_user #12 
- [x] mail_message_external #10 
- [x] mail_log_message_to_process #7 
- [x] partner_mail_message_view #9 
- [x] fetchmail_fetch_missing #8
- [x] mail_create_partner #20 
- [ ] mail_check_immediately #21 (needs some fix)
- [ ] mail_sent #22
- [ ] mail_move_message #24 (needs some fix)
- web_polymorphic #6 
- mail_all #23
- mail_base #5

**Comment by AaronHForgeFlow** [comment]
ping @mreficent @jbeficent

**Comment by AaronHForgeFlow** [comment]
@mreficent https://github.com/Eficent/mailbox_replica/tree/7.0/mail_outgoing was not migrated because it is covered? Is it?

**Comment by MiquelRForgeFlow** [comment]
I don't know, I just migrated the modules listed in the shared doc

**Comment by AaronHForgeFlow** [comment]
Well it does not matter. It shows the emails on queue to be delivered. That is not the most important feature.
